---
title: "user_eval_test"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(stringr)

df = read.csv("study_result.csv")
df <- df %>%
  mutate(Interface = ifelse(Interface == "ASPredicted", "AsPredicted", Interface))
df
```

```{r}
df$Participant = factor(df$Participant)
df$Interface = factor(df$Interface)
df$Order = factor(df$Order)

x = function(data) {
  v = unlist(str_split(data, "\\."))[[1]]
  print((as.numeric(v[1]) * 60 + as.numeric(v[2]) + as.numeric(v[3]) / 100))
  return(as.numeric(v[1]) * 60 + as.numeric(v[2]) + as.numeric(v[3]) / 100)
}


df$Seconds = sapply(df$Time, function(data) {
  v = str_split(data, "\\.|:")[[1]]
  print(v)
  value = (as.numeric(v[1]) * 60 + as.numeric(v[2]) + as.numeric(v[3]) / 100)
  return(value)
})
df
```

```{r}
library(plyr)
ddply(df, ~ Interface, function(data) summary(data$Seconds))

#ggplot(df, aes(x=Interface, y=Seconds)) + geom_boxplot()
boxplot(Seconds ~ Interface, data=df, vert=FALSE)
```
```{r}
shapiro.test(df[df$Interface == "Aperitif",]$Seconds)
shapiro.test(df[df$Interface == "AsPredicted",]$Seconds)
```

```{r}
library(car)
leveneTest(Seconds ~ Interface, data=df, center=median)
```

```{r}
library(reshape2)

df.wide.order = dcast(df, Participant ~ Order, value.var="Seconds")
t.test(df.wide.order$"1", df.wide.order$"2", paired=TRUE, var.equal=TRUE)
```

```{r}
df.wide.order = dcast(df, Participant ~ Interface, value.var="Seconds")
t.test(df.wide.order$AsPredicted,df.wide.order$Aperitif, paired=TRUE, var.equal=TRUE)
```
```{r}
df
```

```{r}

boxplot(Seconds ~ Interface, data=df, horizontal=TRUE)
```

```{r}
ddply(df, ~ Interface, summarise, Seconds.mean=mean(Seconds), Seconds.sd = sd(Seconds))

```


```{r}
questions = rep(c("Aperitif improves my confidence in the scientific rigor of my research plan compared to the original template.",
        "Aperitif reduces the efforts of my preregistration process compared to the original template. ",
        "Aperitif makes me more likely to preregister my future studies compared to using the original template.",
        "Aperitif makes me more likely to use power analysis when preregistering the study compared to using the original template. ",
        "I will likely refer to the statistical analysis code and report generated by Aperitif after my preregistration. "), each=5)

questions = rep(c("Improve the confidence in scientific rigor", "Reduce the efforts of preregistration", "More likely to preregister future studies", "More likely to use power analysis", "Refer to the statistical analysis code and method section"), each=5)
categories = rep(c("Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"), 5)
colors <- rep(c("#FF00E2", "#B2009E", "#45FF00", "#40A819", "#6BB251"), 5)
total = c(0, 0, 2, 9, 6,
          0, 0, 1, 5, 11,
          0, 0, 3, 8, 6,
          0, 0, 2, 3, 12,
          0, 1, 1, 2, 13)
question_id = rep(c(1,2,3,4,5), each=5)

survey_df = data.frame(question = questions, category=categories, total=total, countT = 17, question_id=question_id, color=colors)
survey_df$per = survey_df$total / survey_df$countT
survey_df
```
```{r}

survey_df$newQuestions = str_wrap(survey_df$question, width = 50)
survey_df$category = factor(survey_df$category, levels=c('Strongly Agree', 'Agree', 'Neutral', "Disagree", "Strongly Disagree"))
survey_df$question_id = factor(survey_df$question_id, levels=c(1,2,3,4,5))

survey_df
```
```{r}
survey_df$total
```


```{r}
library(ggplot2)
myColors <- c("#6BB251","#40A819","#45FF00","#B2009E", "#FF00E2")

png(filename="questionnaire_result.png", width=800, height=300)

g3 <- ggplot(survey_df, aes(fill=factor(category), y=total, x=newQuestions)) + 
  geom_bar(position="fill", stat="identity") +
  scale_fill_manual(values=myColors, guide = guide_legend(reverse = TRUE)) +
  coord_flip() + 
  ylab("Percentage") + 
  xlab("Question") +
  theme(legend.title = element_blank(), legend.position="bottom", legend.box = "horizontal")

ggsave(g3, file="~/Desktop/survey_result.svg")
```

